In [1]:
import nltk

In [2]:
import re

In [3]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

## Dataset is available here...
https://archive.ics.uci.edu/ml/datasets/SMS+Spam+Collection

In [4]:
import pandas as pd

In [5]:
messages = pd.read_csv('SMSSpamCollection', sep='\t', names=['label','message'])

In [6]:
messages.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [7]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [8]:
corpus=[]
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['message'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [9]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

In [10]:
# Creating the Bag of Words model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=2500)
X = cv.fit_transform(corpus).toarray()
y = pd.get_dummies(messages['label'])
y=y.iloc[:,1].values

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

## Training model using Naive bayes classifier

In [13]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB().fit(X_train, y_train)

In [14]:
y_pred = model.predict(X_test)

In [15]:
y_pred

array([0, 1, 0, ..., 0, 1, 0], dtype=uint8)

In [16]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [17]:
conf_matrix = confusion_matrix(y_test, y_pred)

In [18]:
conf_matrix

array([[946,   9],
       [  7, 153]], dtype=int64)

In [19]:
accuracy = accuracy_score(y_test, y_pred)

In [20]:
accuracy

0.9856502242152466

## Using Lemmatization and Tf-idf Vectorizer

In [21]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [22]:
corpus1 = []
for i in range(len(messages)):
    review = re.sub('^a-zA-Z', ' ', messages['message'][i])
    review = review.lower()
    review = review.split()
    review = [lemmatizer.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus1.append(review)  

In [23]:
corpus1

['go jurong point, crazy.. available bugis n great world la e buffet... cine got amore wat...',
 'ok lar... joking wif u oni...',
 "free entry 2 wkly comp win fa cup final tkts 21st may 2005. text fa 87121 receive entry question(std txt rate)t&c's apply 08452810075over18's",
 'u dun say early hor... u c already say...',
 'nah think go usf, life around though',
 "freemsg hey darling 3 week's word back! i'd like fun still? tb ok! xxx std chgs send, £1.50 rcv",
 'even brother like speak me. treat like aid patent.',
 "per request 'melle melle (oru minnaminunginte nurungu vettam)' set callertune callers. press *9 copy friend callertune",
 'winner!! valued network customer selected receivea £900 prize reward! claim call 09061701461. claim code kl341. valid 12 hour only.',
 'mobile 11 month more? u r entitled update latest colour mobile camera free! call mobile update co free 08002986030',
 "i'm gonna home soon want talk stuff anymore tonight, k? i've cried enough today.",
 'six chance win ca

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer(max_features=2500)
X1 = tf.fit_transform(corpus1).toarray()

In [27]:
X1_train, X1_test, y_train, y_test = train_test_split(X1, y, test_size = 0.20, random_state = 0)

In [28]:
from sklearn.naive_bayes import MultinomialNB
model1 = MultinomialNB().fit(X1_train, y_train)

In [29]:
y_pred1 = model1.predict(X1_test)

In [30]:
conf_matrix1 = confusion_matrix(y_test, y_pred1)

In [31]:
conf_matrix1

array([[955,   0],
       [ 18, 142]], dtype=int64)

In [32]:
accuracy1 = accuracy_score(y_test, y_pred1)

In [33]:
accuracy1

0.9838565022421525